-- MySQL Script generated by MySQL Workbench
-- Fri Mar 30 15:42:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

USE `ESCAPADE` ;
-- -----------------------------------------------------
-- Table `Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Client` (
  `idClient` VARCHAR(15) NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `adresse` VARCHAR(50) NULL,
  `email` VARCHAR(50) NULL,
  `num_tel` VARCHAR(20) NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parking` (
  `idParking` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `adresse` VARCHAR(100) NULL,
  PRIMARY KEY (`idParking`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Controleur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Controleur` (
  `idControleur` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  PRIMARY KEY (`idControleur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Voiture`
-- -----------------------------------------------------
CREATE TABLE  `Voiture` (
  `idVoiture` VARCHAR(20) NOT NULL,
  `num_place` VARCHAR(2) NULL,
  `marque` VARCHAR(25) NULL,
  `model` VARCHAR(45) NULL,
  `etat_location` VARCHAR(45) NULL,
  `Parking_idParking` INT NOT NULL,
  `Controleur_idControleur` INT NOT NULL,
  PRIMARY KEY (`idVoiture`, `Parking_idParking`, `Controleur_idControleur`),
  INDEX `fk_Voiture_Parking1_idx` (`Parking_idParking` ASC),
  INDEX `fk_Voiture_Controleur1_idx` (`Controleur_idControleur` ASC),
  CONSTRAINT `fk_Voiture_Parking1`
    FOREIGN KEY (`Parking_idParking`)
    REFERENCES `Parking` (`idParking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voiture_Controleur1`
    FOREIGN KEY (`Controleur_idControleur`)
    REFERENCES `Controleur` (`idControleur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Logement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logement` (
  `adresse` VARCHAR(20) NOT NULL,
  `nom_etablissement` VARCHAR(45) NULL,
  PRIMARY KEY (`adresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Theme` (
  `nomTheme` VARCHAR(3) NOT NULL,
  `departement` INT NULL,
  PRIMARY KEY (`nomTheme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sejour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sejour` (
  `idSejour` VARCHAR(25) NOT NULL,
  `date` VARCHAR(45) NULL,
  `note` INT NULL,
  `commentaire_sejour` VARCHAR(100) NULL,
  `Voiture_idVoiture` VARCHAR(20) NOT NULL,
  `Logement_adresse` VARCHAR(20) NOT NULL,
  `Client_idClient` VARCHAR(15) NOT NULL,
  `Theme_nomTheme` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idSejour`, `Voiture_idVoiture`, `Logement_adresse`, `Client_idClient`, `Theme_nomTheme`),
  INDEX `fk_Sejour_Voiture1_idx` (`Voiture_idVoiture` ASC),
  INDEX `fk_Sejour_Logement1_idx` (`Logement_adresse` ASC),
  INDEX `fk_Sejour_Client1_idx` (`Client_idClient` ASC),
  INDEX `fk_Sejour_Theme1_idx` (`Theme_nomTheme` ASC),
  CONSTRAINT `fk_Sejour_Voiture1`
    FOREIGN KEY (`Voiture_idVoiture`)
    REFERENCES `Voiture` (`idVoiture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sejour_Logement1`
    FOREIGN KEY (`Logement_adresse`)
    REFERENCES `Logement` (`adresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sejour_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sejour_Theme1`
    FOREIGN KEY (`Theme_nomTheme`)
    REFERENCES `Theme` (`nomTheme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Maintenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Maintenance` (
  `idMaintenance` INT NOT NULL,
  `motif_maintenance` VARCHAR(45) NULL,
  `modification_par_controleur` VARCHAR(200) NULL,
  `Voiture_idVoiture` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idMaintenance`, `Voiture_idVoiture`),
  INDEX `fk_Maintenance_Voiture1_idx` (`Voiture_idVoiture` ASC),
  CONSTRAINT `fk_Maintenance_Voiture1`
    FOREIGN KEY (`Voiture_idVoiture`)
    REFERENCES `Voiture` (`idVoiture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
